set_property SRC_FILE_INFO {cfile:E:/Desktop/Work/Class/Class2_Program/SM3/project_1/project_1.srcs/constrs_1/new/bOARD.xdc rfile:../../../project_1.srcs/constrs_1/new/bOARD.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC23 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD HSTL_II_18 [get_ports i_clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AD21 [get_ports {o_led[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF25 [get_ports {o_led[1]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF24 [get_ports {o_led[2]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE25 [get_ports {o_led[3]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list i_clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets i_clk_IBUF_BUFG]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC23 [get_ports i_clk_p]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 256 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {w_Encrypt_Data[0]} {w_Encrypt_Data[1]} {w_Encrypt_Data[2]} {w_Encrypt_Data[3]} {w_Encrypt_Data[4]} {w_Encrypt_Data[5]} {w_Encrypt_Data[6]} {w_Encrypt_Data[7]} {w_Encrypt_Data[8]} {w_Encrypt_Data[9]} {w_Encrypt_Data[10]} {w_Encrypt_Data[11]} {w_Encrypt_Data[12]} {w_Encrypt_Data[13]} {w_Encrypt_Data[14]} {w_Encrypt_Data[15]} {w_Encrypt_Data[16]} {w_Encrypt_Data[17]} {w_Encrypt_Data[18]} {w_Encrypt_Data[19]} {w_Encrypt_Data[20]} {w_Encrypt_Data[21]} {w_Encrypt_Data[22]} {w_Encrypt_Data[23]} {w_Encrypt_Data[24]} {w_Encrypt_Data[25]} {w_Encrypt_Data[26]} {w_Encrypt_Data[27]} {w_Encrypt_Data[28]} {w_Encrypt_Data[29]} {w_Encrypt_Data[30]} {w_Encrypt_Data[31]} {w_Encrypt_Data[32]} {w_Encrypt_Data[33]} {w_Encrypt_Data[34]} {w_Encrypt_Data[35]} {w_Encrypt_Data[36]} {w_Encrypt_Data[37]} {w_Encrypt_Data[38]} {w_Encrypt_Data[39]} {w_Encrypt_Data[40]} {w_Encrypt_Data[41]} {w_Encrypt_Data[42]} {w_Encrypt_Data[43]} {w_Encrypt_Data[44]} {w_Encrypt_Data[45]} {w_Encrypt_Data[46]} {w_Encrypt_Data[47]} {w_Encrypt_Data[48]} {w_Encrypt_Data[49]} {w_Encrypt_Data[50]} {w_Encrypt_Data[51]} {w_Encrypt_Data[52]} {w_Encrypt_Data[53]} {w_Encrypt_Data[54]} {w_Encrypt_Data[55]} {w_Encrypt_Data[56]} {w_Encrypt_Data[57]} {w_Encrypt_Data[58]} {w_Encrypt_Data[59]} {w_Encrypt_Data[60]} {w_Encrypt_Data[61]} {w_Encrypt_Data[62]} {w_Encrypt_Data[63]} {w_Encrypt_Data[64]} {w_Encrypt_Data[65]} {w_Encrypt_Data[66]} {w_Encrypt_Data[67]} {w_Encrypt_Data[68]} {w_Encrypt_Data[69]} {w_Encrypt_Data[70]} {w_Encrypt_Data[71]} {w_Encrypt_Data[72]} {w_Encrypt_Data[73]} {w_Encrypt_Data[74]} {w_Encrypt_Data[75]} {w_Encrypt_Data[76]} {w_Encrypt_Data[77]} {w_Encrypt_Data[78]} {w_Encrypt_Data[79]} {w_Encrypt_Data[80]} {w_Encrypt_Data[81]} {w_Encrypt_Data[82]} {w_Encrypt_Data[83]} {w_Encrypt_Data[84]} {w_Encrypt_Data[85]} {w_Encrypt_Data[86]} {w_Encrypt_Data[87]} {w_Encrypt_Data[88]} {w_Encrypt_Data[89]} {w_Encrypt_Data[90]} {w_Encrypt_Data[91]} {w_Encrypt_Data[92]} {w_Encrypt_Data[93]} {w_Encrypt_Data[94]} {w_Encrypt_Data[95]} {w_Encrypt_Data[96]} {w_Encrypt_Data[97]} {w_Encrypt_Data[98]} {w_Encrypt_Data[99]} {w_Encrypt_Data[100]} {w_Encrypt_Data[101]} {w_Encrypt_Data[102]} {w_Encrypt_Data[103]} {w_Encrypt_Data[104]} {w_Encrypt_Data[105]} {w_Encrypt_Data[106]} {w_Encrypt_Data[107]} {w_Encrypt_Data[108]} {w_Encrypt_Data[109]} {w_Encrypt_Data[110]} {w_Encrypt_Data[111]} {w_Encrypt_Data[112]} {w_Encrypt_Data[113]} {w_Encrypt_Data[114]} {w_Encrypt_Data[115]} {w_Encrypt_Data[116]} {w_Encrypt_Data[117]} {w_Encrypt_Data[118]} {w_Encrypt_Data[119]} {w_Encrypt_Data[120]} {w_Encrypt_Data[121]} {w_Encrypt_Data[122]} {w_Encrypt_Data[123]} {w_Encrypt_Data[124]} {w_Encrypt_Data[125]} {w_Encrypt_Data[126]} {w_Encrypt_Data[127]} {w_Encrypt_Data[128]} {w_Encrypt_Data[129]} {w_Encrypt_Data[130]} {w_Encrypt_Data[131]} {w_Encrypt_Data[132]} {w_Encrypt_Data[133]} {w_Encrypt_Data[134]} {w_Encrypt_Data[135]} {w_Encrypt_Data[136]} {w_Encrypt_Data[137]} {w_Encrypt_Data[138]} {w_Encrypt_Data[139]} {w_Encrypt_Data[140]} {w_Encrypt_Data[141]} {w_Encrypt_Data[142]} {w_Encrypt_Data[143]} {w_Encrypt_Data[144]} {w_Encrypt_Data[145]} {w_Encrypt_Data[146]} {w_Encrypt_Data[147]} {w_Encrypt_Data[148]} {w_Encrypt_Data[149]} {w_Encrypt_Data[150]} {w_Encrypt_Data[151]} {w_Encrypt_Data[152]} {w_Encrypt_Data[153]} {w_Encrypt_Data[154]} {w_Encrypt_Data[155]} {w_Encrypt_Data[156]} {w_Encrypt_Data[157]} {w_Encrypt_Data[158]} {w_Encrypt_Data[159]} {w_Encrypt_Data[160]} {w_Encrypt_Data[161]} {w_Encrypt_Data[162]} {w_Encrypt_Data[163]} {w_Encrypt_Data[164]} {w_Encrypt_Data[165]} {w_Encrypt_Data[166]} {w_Encrypt_Data[167]} {w_Encrypt_Data[168]} {w_Encrypt_Data[169]} {w_Encrypt_Data[170]} {w_Encrypt_Data[171]} {w_Encrypt_Data[172]} {w_Encrypt_Data[173]} {w_Encrypt_Data[174]} {w_Encrypt_Data[175]} {w_Encrypt_Data[176]} {w_Encrypt_Data[177]} {w_Encrypt_Data[178]} {w_Encrypt_Data[179]} {w_Encrypt_Data[180]} {w_Encrypt_Data[181]} {w_Encrypt_Data[182]} {w_Encrypt_Data[183]} {w_Encrypt_Data[184]} {w_Encrypt_Data[185]} {w_Encrypt_Data[186]} {w_Encrypt_Data[187]} {w_Encrypt_Data[188]} {w_Encrypt_Data[189]} {w_Encrypt_Data[190]} {w_Encrypt_Data[191]} {w_Encrypt_Data[192]} {w_Encrypt_Data[193]} {w_Encrypt_Data[194]} {w_Encrypt_Data[195]} {w_Encrypt_Data[196]} {w_Encrypt_Data[197]} {w_Encrypt_Data[198]} {w_Encrypt_Data[199]} {w_Encrypt_Data[200]} {w_Encrypt_Data[201]} {w_Encrypt_Data[202]} {w_Encrypt_Data[203]} {w_Encrypt_Data[204]} {w_Encrypt_Data[205]} {w_Encrypt_Data[206]} {w_Encrypt_Data[207]} {w_Encrypt_Data[208]} {w_Encrypt_Data[209]} {w_Encrypt_Data[210]} {w_Encrypt_Data[211]} {w_Encrypt_Data[212]} {w_Encrypt_Data[213]} {w_Encrypt_Data[214]} {w_Encrypt_Data[215]} {w_Encrypt_Data[216]} {w_Encrypt_Data[217]} {w_Encrypt_Data[218]} {w_Encrypt_Data[219]} {w_Encrypt_Data[220]} {w_Encrypt_Data[221]} {w_Encrypt_Data[222]} {w_Encrypt_Data[223]} {w_Encrypt_Data[224]} {w_Encrypt_Data[225]} {w_Encrypt_Data[226]} {w_Encrypt_Data[227]} {w_Encrypt_Data[228]} {w_Encrypt_Data[229]} {w_Encrypt_Data[230]} {w_Encrypt_Data[231]} {w_Encrypt_Data[232]} {w_Encrypt_Data[233]} {w_Encrypt_Data[234]} {w_Encrypt_Data[235]} {w_Encrypt_Data[236]} {w_Encrypt_Data[237]} {w_Encrypt_Data[238]} {w_Encrypt_Data[239]} {w_Encrypt_Data[240]} {w_Encrypt_Data[241]} {w_Encrypt_Data[242]} {w_Encrypt_Data[243]} {w_Encrypt_Data[244]} {w_Encrypt_Data[245]} {w_Encrypt_Data[246]} {w_Encrypt_Data[247]} {w_Encrypt_Data[248]} {w_Encrypt_Data[249]} {w_Encrypt_Data[250]} {w_Encrypt_Data[251]} {w_Encrypt_Data[252]} {w_Encrypt_Data[253]} {w_Encrypt_Data[254]} {w_Encrypt_Data[255]}]]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list w_Encrypt_Valid]]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
