webtalk_init -webtalk_dir E:/Desktop/Work/Class/Class2_Program/SM3/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/SIM_sm3_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 27 21:32:47 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e71060e2-f1ac-4aba-9dbf-b1d4af1a149b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "be1a3f5ff85f4060a9a9dc98b65d9bdf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "204" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-14900KF" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3187 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15476_KB" -context "xsim\\usage"
webtalk_transmit -clientid 239414133 -regid "" -xml E:/Desktop/Work/Class/Class2_Program/SM3/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/SIM_sm3_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Desktop/Work/Class/Class2_Program/SM3/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/SIM_sm3_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Desktop/Work/Class/Class2_Program/SM3/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/SIM_sm3_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
